# Generated by Django 3.1.5 on 2021-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=25)),
                ('url', models.TextField()),
                ('cols', models.TextField()),
                ('owner', models.CharField(max_length=10)),
            ],
        ),
    ]
